### ISSUE TITLE
[feature] : JWT 사용해서 로그인하기

### ISSUE THREAD

**Issue by harimrim** [heart-muscle/heart-muscle-backend#10]
- 스프링 시큐리티에서 JWT 방식으로 로그인하기

**Comment by harimrim** [comment]
- SecurityConfig 설정
- TokenProvider 에서 토큰 생성 및 소멸 주기 설정
- application 에서 JWT 의존성 추가
- JwtFilter 로 token 유효성 검증하기

**Comment by siyoungoh** [comment]
ㅇㅋㄷㅋ
- SecurityConfig 설정 - 30min
- application 에서 JWT 의존성 추가 - 10min

ㅈㅁㄹㄱㅇ
- TokenProvider 에서 토큰 생성 및 소멸 주기 설정 - ??? / learning : 12h 
  - why? 왜 더/덜 걸렸지? 
    - 예. 강의가 별로 도움이 되지 않아서 새로운 레퍼런스를 찾았다. 
      - Try: 그 레퍼런스가 진짜로 도움이 되는지 검토 먼저 해보자.
- JwtFilter 로 token 유효성 검증하기 - ??? / learning : 6h

**Comment by siyoungoh** [comment]
이거 말고 더 비용이 적은(시간이 덜걸리는, 더 재밌는,...) 방법은 없나? 
진짜 이거 내가 지금 해야하나? 
이거 하면 내가 달성할 수 있나?
